### ISSUE TITLE
Incompatible glyphs "uniA738" in NotoSansDisplayRoman-MM.glyphs

### ISSUE THREAD

**Issue by xiangyexiao** [googlei18n/noto-fonts#799]
I ran this command
$fontmake -g src/NotoSansDisplayRoman-MM.glyphs -o variable

and got this error message:
>> Building interpolation-compatible TTFs
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/__main__.py", line 109, in main
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 317, in run_from_glyphs
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 358, in run_from_designspace
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 423, in run_from_ufos
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 178, in build_interpolatable_ttfs
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 138, in convert_curves
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/cu2qu/ufo.py", line 195, in fonts_to_quadratic
    _fonts_to_quadratic(fonts, max_errors, reverse_direction, stats)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/cu2qu/ufo.py", line 155, in _fonts_to_quadratic
    'Incompatible glyphs "%s"' % name)
AssertionError: Incompatible glyphs "uniA738"

**Comment by marekjez86** [comment]
NotoSansDisplayRoman-MM.glyphs is an OLD, deprecated source. Please use NotoSansDisplay-MM.glyphs
